-- Initial Printout modular-monolith schema. Generated migration is intentionally checked in.
CREATE TYPE "Role" AS ENUM ('SHOP_OWNER','PLATFORM_ADMIN'); CREATE TYPE "ShopStatus" AS ENUM ('ACTIVE','SUSPENDED'); CREATE TYPE "OrderStatus" AS ENUM ('NEW','ACCEPTED','PRINTING','PRINTED','READY','COLLECTED','CANCELLED','EXPIRED'); CREATE TYPE "DocumentStatus" AS ENUM ('UPLOADING','AVAILABLE','PRINTED_RETENTION','DELETED','FAILED'); CREATE TYPE "ColourMode" AS ENUM ('bw','colour'); CREATE TYPE "PrintSides" AS ENUM ('single','duplex'); CREATE TYPE "SubscriptionStatus" AS ENUM ('ACTIVE','SUSPENDED','CANCELLED');
CREATE TABLE "Shop" ("id" TEXT PRIMARY KEY,"slug" TEXT NOT NULL UNIQUE,"displayName" TEXT NOT NULL,"address" TEXT,"status" "ShopStatus" NOT NULL DEFAULT 'ACTIVE',"acceptsOrders" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "User" ("id" TEXT PRIMARY KEY,"shopId" TEXT,"email" TEXT NOT NULL UNIQUE,"displayName" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"role" "Role" NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL, FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE SET NULL);
CREATE TABLE "Session" ("id" TEXT PRIMARY KEY,"tokenHash" TEXT NOT NULL UNIQUE,"userId" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"invalidatedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE);
CREATE TABLE "ShopSettings" ("id" TEXT PRIMARY KEY,"shopId" TEXT NOT NULL UNIQUE,"publicContact" TEXT,"brandColor" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL, FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE);
CREATE TABLE "PricingRule" ("id" TEXT PRIMARY KEY,"shopId" TEXT NOT NULL,"paperSize" TEXT NOT NULL DEFAULT 'A4',"colourMode" "ColourMode" NOT NULL,"sides" "PrintSides" NOT NULL,"pricePerSheetPaise" INTEGER NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL, UNIQUE("shopId","paperSize","colourMode","sides"), FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE);
CREATE TABLE "Document" ("id" TEXT PRIMARY KEY,"shopId" TEXT NOT NULL,"objectKey" TEXT NOT NULL UNIQUE,"originalFilename" TEXT NOT NULL,"detectedMimeType" TEXT,"byteSize" BIGINT,"pageCount" INTEGER,"checksum" TEXT,"status" "DocumentStatus" NOT NULL DEFAULT 'UPLOADING',"uploadedAt" TIMESTAMP(3),"expiresAt" TIMESTAMP(3),"printedAt" TIMESTAMP(3),"deleteAfter" TIMESTAMP(3),"deletedAt" TIMESTAMP(3),"deletionError" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL, FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE);
CREATE TABLE "Order" ("id" TEXT PRIMARY KEY,"shopId" TEXT NOT NULL,"documentId" TEXT NOT NULL UNIQUE,"orderNumber" TEXT NOT NULL UNIQUE,"trackingToken" TEXT NOT NULL UNIQUE,"customerDisplayNameOrReference" TEXT,"status" "OrderStatus" NOT NULL DEFAULT 'NEW',"totalPaise" INTEGER NOT NULL,"currency" TEXT NOT NULL DEFAULT 'INR',"priceSnapshot" JSONB NOT NULL,"printOptionsSnapshot" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL, FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE, FOREIGN KEY ("documentId") REFERENCES "Document"("id"));
CREATE TABLE "OrderStatusHistory" ("id" TEXT PRIMARY KEY,"orderId" TEXT NOT NULL,"fromStatus" "OrderStatus","toStatus" "OrderStatus" NOT NULL,"reason" TEXT,"actorUserId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE CASCADE);
CREATE TABLE "Plan" ("id" TEXT PRIMARY KEY,"name" TEXT NOT NULL UNIQUE,"pricePaise" INTEGER NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "Subscription" ("id" TEXT PRIMARY KEY,"shopId" TEXT NOT NULL UNIQUE,"planId" TEXT NOT NULL,"status" "SubscriptionStatus" NOT NULL DEFAULT 'ACTIVE',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL, FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE CASCADE, FOREIGN KEY ("planId") REFERENCES "Plan"("id"));
CREATE TABLE "AuditLog" ("id" TEXT PRIMARY KEY,"shopId" TEXT,"actorUserId" TEXT,"action" TEXT NOT NULL,"targetType" TEXT,"targetId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY ("shopId") REFERENCES "Shop"("id") ON DELETE SET NULL);
CREATE INDEX "Document_shopId_status_idx" ON "Document"("shopId","status"); CREATE INDEX "Document_status_deleteAfter_idx" ON "Document"("status","deleteAfter"); CREATE INDEX "Document_status_expiresAt_idx" ON "Document"("status","expiresAt"); CREATE INDEX "Order_shopId_status_createdAt_idx" ON "Order"("shopId","status","createdAt"); CREATE INDEX "AuditLog_shopId_createdAt_idx" ON "AuditLog"("shopId","createdAt");
